fixed to check for ~/.ssh-exec fix case on SunOS check

diff --git a/ssh-exec b/ssh-exec
--- a/ssh-exec
+++ b/ssh-exec
@@ -19,7 +19,7 @@
 set -u
 
 # os check
-[[ "$(uname -s)" != 'SunOs' ]] || { echo 'ERROR: this script is known not to work on Solaris'; exit 1; }
+[[ "$(uname -s)" != 'SunOS' ]] || { echo 'ERROR: this script is known not to work on Solaris'; exit 1; }
 
 # dependency check
 [[ "$(which expect)" ]] || { echo 'ERROR: expect command is not available'; exit 1; }
@@ -638,42 +638,44 @@ parse_tokens () {
 
     echo "$commands" > "$commands_file"
 
-    # load user defined tokens
-    tokens=
-    for token_file in $recipes_dir/*; do
-        if [[ "$tokens" ]]; then
-            tokens="${tokens}|^#${token_file##*/}"
-        else
-            tokens="^#${token_file##*/}"
-        fi
-    done
+    if [[ -d "$recipes_dir" ]]; then
+        # load user defined tokens
+        tokens=
+        for token_file in $recipes_dir/*; do
+            if [[ "$tokens" ]]; then
+                tokens="${tokens}|^#${token_file##*/}"
+            else
+                tokens="^#${token_file##*/}"
+            fi
+        done
 
-    # expand user defined tokens
-    while read token args <<<$(egrep -n "$tokens" "$commands_file" | head -1 | sed -e 's/#\(.*\)/\1/' -e 's/#$//'); do
-        # if no tokens are found we're done
-        [[ -z "$token" ]] && break
+        # expand user defined tokens
+        while read token args <<<$(egrep -n "$tokens" "$commands_file" | head -1 | sed -e 's/#\(.*\)/\1/' -e 's/#$//'); do
+            # if no tokens are found we're done
+            [[ -z "$token" ]] && break
 
-        read line token <<<$(sed 's/:/ /' <<<"$token")
+            read line token <<<$(sed 's/:/ /' <<<"$token")
 
-        # load recipe from associated token file
-        recipe=$(cat "${recipes_dir}/$token")
+            # load recipe from associated token file
+            recipe=$(cat "${recipes_dir}/$token")
 
-        # replace args within recipe
-        count=1
-        while read arg; do
-            recipe=$(sed "s/\$arg${count}/$arg/g" <<<"$recipe")
-            ((count+=1))
-        done < <(eval "for arg in $args; do echo \$arg; done")
+            # replace args within recipe
+            count=1
+            while read arg; do
+                recipe=$(sed "s/\$arg${count}/$arg/g" <<<"$recipe")
+                ((count+=1))
+            done < <(eval "for arg in $args; do echo \$arg; done")
 
-        # sanity check for missing args
-        grep -q '$arg[[:digit:]]' <<<"$recipe" && { echo "ERROR: missing argument for token: $token"; exit 1; }
+            # sanity check for missing args
+            grep -q '$arg[[:digit:]]' <<<"$recipe" && { echo "ERROR: missing argument for token: $token"; exit 1; }
 
-        # replace token with associated recipe
-        sed "$line r /dev/stdin" "$commands_file" > "${commands_file}.tmp" <<<"$recipe"
+            # replace token with associated recipe
+            sed "$line r /dev/stdin" "$commands_file" > "${commands_file}.tmp" <<<"$recipe"
 
-        # remove token
-        sed "${line}d" "${commands_file}.tmp" > "$commands_file"
-    done
+            # remove token
+            sed "${line}d" "${commands_file}.tmp" > "$commands_file"
+        done
+    fi
 
     # expand built-in #passwd# token
     while grep -q '^#passwd' "$commands_file"; do
